shellcheck, now POSIX-compliant

diff --git a/zathura-pywal b/zathura-pywal
--- a/zathura-pywal
+++ b/zathura-pywal
@@ -1,50 +1,75 @@
 #!/bin/sh
 #
-# A better version of zathura-pywal that saves settings and features alpha transparency
+# zathura-pywal
 
-zathurarc="/home/$(whoami)/.config/zathura/zathurarc"
-grepdir="/usr/share/zathura-pywal/settings"
-colors="/home/$(whoami)/.cache/wal/colors.sh"
+NEWLINE='
+'
+ZATHURA_DIR="${XDG_CONFIG_HOME:-${HOME}/.config/}/zathura/"
+ZATHURARC="${ZATHURA_DIR}/zathurarc"
+GREPDIR="/usr/share/zathura-pywal/settings"
+COLORS="${XDG_CACHE_HOME:-${HOME}/.cache/}/wal/colors.sh"
 
 usage() {
-  printf "Usage: $(basename $0) [options]\n" 1>&2;
-  printf 'Options:\n'
-  printf -- '-a%-6sAlpha transparency of the background (default: 1)\n'
-  printf -- '-h%-6sDisplay this prompt\n'
-  exit 1;
+    printf '%s\n' "Usage: $(basename "${0}") [options]" 1>&2;
+    printf 'Options:\n'
+    printf '%s%-6sAlpha transparency of the background (default: 1)\n' '-a' ''
+    printf '%s%-6sDisplay this prompt\n' '-h' ''
 }
 
 zathura_pywal() {
-  printf 'Checking for zathurarc...\n'
-  sleep 0.2s
-  [ -f "${zathurarc}" ] && { printf "Backing up zathurarc...\n"; settings="$(grep -v -f ${grepdir} ${zathurarc} | sed '/^$/d' )"; cp "${zathurarc}" "${zathurarc}.bak" ; } \
-                        || { printf "Creating zathurarc...\n"; touch "${zathurarc}" ; }
-  sleep 0.2s
-  printf 'Checking for pywal color scheme...\n'
-  sleep 0.2s
-  { [ -f "${colors}" ] && . "${colors}" ; } || { printf 'Pywal color scheme not found.\nPlease make sure you run pywal in order to generate a colorscheme.\n' && exit 1; }
-    cat /dev/null > "${zathurarc}"
-    [ -n "${settings}" ] && { printf 'Copying old settings into zathurarc...\n' && sleep 0.2s && echo "### Settings from original zathurarc ###
-${settings}
-" >> "${zathurarc}" ; }
-  printf 'Changing zathura color scheme...\n'
-  sleep 0.2s
-  hex="${color0:1}"
-  r="$(printf "%d" 0x${hex:0:2})"
-  g="$(printf "%d" 0x${hex:2:2})"
-  b="$(printf "%d" 0x${hex:4:2})"
-  [ -z "${alpha}" ] && alpha=1
-  [ "${alpha::1}" == "." ] && alpha="${alpha/./0.}"
-  alpha="${alpha:0:4}"
-  echo "### General recoloring settings ###
-# Allow recoloring
+    printf 'Checking for zathurarc...\n'
+    if [ -f "${ZATHURARC}" ]; then
+        printf 'Backing up zathurarc...\n'
+        settings="$(grep -v -f "${GREPDIR}" "${ZATHURARC}" | sed '/^$/d' )"
+        cp "${ZATHURARC}" "${ZATHURARC}.bak"
+    else
+        printf 'Creating zathurarc...\n'
+        mkdir -p "${ZATHURARC%/*}"
+        touch "${ZATHURARC}"
+    fi
+
+    printf 'Checking for pywal color scheme...\n'
+    if [ -f "${COLORS}" ]; then . "${COLORS}"
+    else
+        printf 'Pywal color scheme not found.\nPlease make sure you run pywal in order to generate a color scheme.\n'
+        return 1
+    fi
+
+    cat /dev/null > "${ZATHURARC}"
+
+    if [ -n "${settings}" ]; then
+        printf 'Copying old settings into zathurarc...\n'
+        printf '%s\n\n' "### Settings from original zathurarc ###${NEWLINE}${settings}" >> "${ZATHURARC}"
+    fi
+
+    printf 'Changing zathura color scheme...\n'
+
+    hex="$(printf '%s' "${color0}" | tr '[:lower:]' '[:upper:]' | tr -d '[:punct:]')"
+
+    a=$(printf '%s' "${hex}" | cut -c 1-2)
+    b=$(printf '%s' "${hex}" | cut -c 3-4)
+    c=$(printf '%s' "${hex}" | cut -c 5-6)
+
+    r=$(printf '%s\n' "ibase=16; ${a}" | bc)
+    g=$(printf '%s\n' "ibase=16; ${b}" | bc)
+    b=$(printf '%s\n' "ibase=16; ${c}" | bc)
+
+    [ -z "${alpha}" ] && alpha=1
+
+    [ "${alpha%"${alpha#?}"}" = '.' ] && alpha="0.${alpha#?}"
+
+    [ ${#alpha} -ge 4 ] && alpha="${alpha%${alpha#????}}"
+
+    printf '%s' "### zathura-pywal ###
+# Allow recolor
 set recolor \"true\"
+
 # Don't allow original hue when recoloring
 set recolor-keephue \"false\"
+
 # Don't keep original image colors while recoloring
 set recolor-reverse-video \"false\"
 
-### Theming ###
 # Command line completion entries
 set completion-fg \"${color7}\"
 set completion-bg \"${color0}\"
@@ -58,7 +83,6 @@ set completion-highlight-fg \"${color0}\"
 set completion-highlight-bg \"${color7}\"
 
 # Default foreground/background color
-# set default-fg # TODO
 set default-bg rgba(${r},${g},${b},${alpha})
 
 # Input bar
@@ -107,28 +131,30 @@ set index-bg \"${color0}\"
 
 # Selected element in index mode
 set index-active-fg \"${color0}\"
-set index-active-bg \"${color7}\"" >> "${zathurarc}"
-  printf "All done.\nPress \'Ctrl\' + \'R\' (or whatever \'recolor\' is mapped to) with zathura open to toggle the color scheme.\n"
+set index-active-bg \"${color7}\"" >> "${ZATHURARC}"
+
+    printf "All done.\nPress 'Ctrl' + 'R' (or whatever 'recolor' is mapped to) with zathura open to toggle the color scheme.\n"
 }
 
 main() {
-  [ $# -eq 0 ] && zathura_pywal
+    [ ${#} -eq 0 ] && zathura_pywal
 
-  while getopts "a:h" o; do
-    case "${o}" in
-      a)
-        alpha="${OPTARG}"
-        if ! echo "${alpha}" | grep -q -P '^0*\.+[0-9]+$|^[0-1]$'; then
-          printf 'Alpha must be a decimal value between 0 and 1.\n'
-          usage
-        fi
-        zathura_pywal ${alpha}
-        ;;
-      h|*)
-        usage
-        ;;
-      esac
-  done
+    while getopts "a:h" o; do
+        case "${o}" in
+            a)
+                alpha="${OPTARG}"
+                if ! printf '%s' "${alpha}" | grep -q -P '^0*\.+[0-9]+$|^[0-1]$'; then
+                    printf 'Alpha must be a decimal value between 0 and 1.\n'
+                    usage
+                    return 1
+                fi
+                zathura_pywal "${alpha}"
+                ;;
+            h|*)
+                usage
+                ;;
+        esac
+    done
 }
 
-main "$@"
+main "${@}"
